# Generated by Django 4.2.17 on 2025-01-10 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0003_gamesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
