# Generated by Django 4.2.17 on 2025-01-14 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0007_remove_friendlist_friends_alter_friendlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetting',
            name='game_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Game_Winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
