# Generated by Django 4.2.17 on 2025-01-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0008_gamesetting_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=255),
        ),
    ]
